server:
  port: ${PORT:8081}
eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    serviceA:
      path: /voterservice/api/**
      serviceId: voter-service
    serviceB:
      path: /api/voter/**
      serviceId: candidate-service